print ('welcome to python programming')
print ('please enter your name')
name = input()
print ('hello mr/miss' + name + 'welcome')
print ('please enter your age')
age = input()
print ('your age will be' + str(int(age)+1) 'in a year' )
print ('the length of your name is : ')
print(len(name))
